name: launcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rti_shared: 
    path: ./../rti_shared
  provider: 6.0.5
  bitsdojo_window: ^0.1.6
  mapsforge_flutter: ^2.0.3
  scroll_snap_list: ^0.9.1
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
