name: launcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rti_shared: 
    path: ./../rti_shared
  provider: 6.0.5
  scroll_snap_list: ^0.9.1
  timer_builder: ^2.0.0
  vector_map_tiles: ^7.3.1
  flutter_map: ^6.1.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: ^0.4.3+1
  sqflite_common_ffi: ^2.3.3
  latlong2: ^0.9.1
  vector_tile_renderer: ^5.2.0
  vector_map_tiles_mbtiles: ^1.0.0
  mbtiles: ^0.4.0   
  flutterpi_gstreamer_video_player: ^0.1.1+1
  video_player: ^2.9.1
  chewie: ^1.5.0
  file: ^7.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  #  - assets/maps/