name: rti_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  quick_usb: ^0.4.0
  buffer: ^1.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
